src/tcpliveplay.c
With a long IP address and a 5 digit port, and filter expression can be 51 bytes long:
`tcp and dst host 192.192.192.192 and dst port 51997`
Adding an additional byte for the terminating NULL, the buffer should be 52 bytes instead of the previous 50.
This fixes a buffer overflow on some systems of the form:
```
*** buffer overflow detected ***: tcpliveplay terminated
======= Backtrace: =========
/lib64/libc.so.6(__fortify_fail+0x37)[0x7f95f78bd507]
/lib64/libc.so.6(+0x1003f0)[0x7f95f78bb3f0]
/lib64/libc.so.6(+0xff849)[0x7f95f78ba849]
/lib64/libc.so.6(_IO_default_xsputn+0xc9)[0x7f95f782f8b9]
/lib64/libc.so.6(_IO_vfprintf+0x11d8)[0x7f95f7800428]
/lib64/libc.so.6(__vsprintf_chk+0x9d)[0x7f95f78ba8ed]
/lib64/libc.so.6(__sprintf_chk+0x7f)[0x7f95f78ba82f]
tcpliveplay[0x4037d0] …
```
=> Expand size of filter buffer to avoid overflows.

src/send_packets.c
The limit check improperly lets an extra packet get sent
When the limit is reached, the program enters a busy loop and does not exit.
This patch sets the abort flag so we exit when the limit is reached as well as fixing the send counter check so we only send the number of packets requested.
=> Stop sending and exit when limit is reached

src/tcpliveplay.c, src/tcpliveplay.h
These modifications were tested with and work with Denx gcc-4.2.2
powerpc-linux compilers.  Contributed from NRL Software Radio Project
=> tcpliveplay - Big Endian and compiler work-around for tcpliveplay

src/send_packets.c, src/tcpreplay_api.c, src/tcpreplay_api.h, src/tcpreplay_opts.def
Add --duration option which lets the user set the number of seconds to  transmit
Implemented similarly to the -L option to break out to the send_packets loop and set the abort flag once we have exceeded the time limit.
=> Add option for limiting transmit by time

configure.ac
Xcode 7 which is now the only App Store available Xcode for OS X Yosemite & OS X El Capitan replaced the `.dylib`s inside Xcode with `.tbd` files which point to the correct location on the system and provide symbols, etc.
Example of the first bit of the `libpcap.A.tdb` file:
```
---
archs:           [ i386, x86_64 ]
platform:        macosx
install-name:    /usr/lib/libpcap.A.dylib
exports:
- archs:           [ i386, x86_64 ]
symbols:         [ ___pcap_atodn, ___pcap_atoin, ___pcap_nametodnaddr,
```
This allows people (even those using 4.1.0) to do something like:
```
./configure --with-libpcap=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr
```
And let that work, rather than having to vendor in an external libpcap, etc. This is …
=> configure.ac: recognise tbd stubs

src/tcpedit/plugins/dlt_linuxsll/linuxsll.c, src/tcpr.h
When capturing network packets with tcpdump using the "all" pseudo-interface, the resulting capture file is in linux cooked format (linux SLL). Furthermore, some packets might be coming from the loopback device depending on the activity of the machine. In such a case, when trying to use tcprewrite to replace the linux SLL header with an ethernet header, the program fails with the following error:
```
$ tcprewrite --dlt=enet --enet-dmac=aa:bb:cc:00:00:00 --enet-smac=dd:ee:ff:00:00:00 -i cooked.pcap -o ether.pcap
Fatal Error in tcpedit.c:tcpedit_packet() line 114:
From ./plugins/dlt_linuxsll/linuxsll.c:dlt_linuxsll_decode() line 201:
DLT_LINUX_SLL pcap's must contain only ethernet packets
```
This pull request address this issue.
=> tcprewrite: Handle loopback for linux cooked capture files (Linux SLL)

configure.ac, src/common/sendpacket.c, src/common/sendpacket.h, src/config.h.in
Tap devices must be up and running before using with tcpreplay.
Tap support in Apple devices works a little bit different and it is not compatible with main flow of tcpreplay.
Patch tested in Linux and FreeBSD with different capture files.
=> Tap device support for Linux and FreeBSD

configure.ac, docs/CHANGELOG, src/common/get.c, src/common/utils.c
Fix for ARM builds. Tested on SheevaPlug, and assume fix will work on Pi2. Also fixed cross compile for [multi-arch](https://wiki.debian.org/Multiarch) builds. For example, can cross compile on x86_64 Debian 8 (Jessie) for SheevaPlug with the following (assuming set up for multi-arch and all required libraries installed):
./configure --host=arm-linux-gnueabi
=> #211 fix build and cross-compile issues on ARM

src/Makefile.am
Hi,
This patches adds the *.h counterpart of all *.def files of src/Makefile.am as BUILT_SOURCES.
This way they should be generated before (for example) tcpreplay_api.c.
This should allow parallel build (It works for me, but I do not know how to test if I missed a target).
Regards,
=> declare the headers generated by autoopts as BUILT_SOURCES

README.md
when i run the old line i see:
```
$ git clone git@github.com:appneta/tcpreplay.git
Cloning into 'tcpreplay'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
=> make clone https so it works for non-contributors

src/send_packets.c
Hi,
Currently, the next packet sent time is based on the previous packet. When a lot of packets are sent, a small jitter may be inserted and all subsequent packet will have the same added jitter; tcpreplay will not recover from this jitter. 
The proposed improvement add a comparison with the system time to recover from those timestamp drift. It also avoid updating the system time and sleeping when there is a jitter to recover from.
Regards.
=> Add protection against packet drift.

.travis.yml
OS X builds taking too long, so only test clang with XCode 8.2
=> Reduce Travis CL build times

src/Makefile.am
This should fix parallel build.
I don't know why I stumbled upon it just now.
=> add tcpreplay_opts.h to list of BUILT_SOURCES

configure.ac
Latest changes caused multiple declarations of $VERSION and $PRODUCT, which caused `configure` test failures. The result was that tests failed where they otherwise would pass. Result was `-Wno-format-contains-nul` was not defined.
Fix is to remove effectively duplicate declarations of the within `configure.ac`.
=> Enhancement #334 - Fix warnings on debug

src/tcpedit/fuzzing.c
For example, this means :
- skipping TCP SYN packets
- no ethertype, ip addresses, not port number will be modified
Signed-off-by: Gabriel Ganne <gabriel.ganne@enea.com>
=> fuzzing  ignores layers 2, 3, and 4

src/replay.c, src/send_packets.c
Assume every file starts a new replay session, so reset the time this
session started, the time last packet was sent, and the timestamp of
the first packet in this trace.  Don't reset the global start time so
that stats are correct.
=> Fix sleep calculation when using multiple pcap files

src/tcpedit/portmap.c
I removed the unnecessary check and fixed the problem with incorrect parsing. This is my first pull request in Open Source.
=> Change(portmap.c): tcprewrite range of ports with --portmap worked fine

src/tcprewrite.c
While on BSD systems, tcprewrite likely sets `O_NDELAY` which is 
proper for most posix systems as this is the newer flag and they 
likely treat both similarly. However BSD and unix derivatives should 
likely utilize `FIONBIO` due to known issues with reading from tty 
with a 0 byte read returning -1 opposed to 0.
Reference comment 1: https://stackoverflow.com/questions/1150635/unix-nonblocking-i-o-o-nonblock-vs-fionbio
on behalf of Cisco Talos
=> Avoid non-blocking behaviour when using STDIN

docs/CHANGELOG, src/common/tcpdump.c, src/common/tcpdump.h, src/replay.c
Reworked how `tcpdump` picks up STDIN/STDOUT pipes. Converted from
old-style socket pairs to modern `pipe` structures.
Found that on 64-bit machines, `struct pcap_pkthdr` is not the same
size as the similar array in the actual PCAP file. Added a new
structure to compensate.
Reworked `poll`, `write` and `read` to make them more robust.
Works on Linux. Still haveing some issues on macOS.
=> Bug #398 Rewrite of tcpdump.c

configure.ac, docs/CHANGELOG, src/config.h.in, src/tcpprep.c
Found a limit of 65K packets for reporting cache files. Removed.
=> Bug #423 Remove limit for tcpprep -S

src/fragroute/bget.c
issue detected by cppcheck
[src/fragroute/bget.c:814] -> [src/fragroute/bget.c:818]: (warning) Either the condition 'buf!=NULL' is redundant or there is overflow in pointer subtraction.
=> resolve possible null pointer dereference

configure.ac, docs/CHANGELOG, src/common/utils.c, src/common/utils.h, src/config.h.in, src/send_packets.c, src/tcpliveplay.c, src/tcpprep.c, src/tcprewrite.c
* Check for packets that are larger than 262144 bytes
* Check for capture lengths that are greater than packet length
Example of a corrupt PCAP file ...
sudo src/tcpreplay -i ens33 --unique-ip -t --loop 4 get_next_paket_01
safe_pcap_next ERROR: Invalid packet length in send_packets.c:get_next_packet() line 1054: 8388670 is greater than maximum 262144
=> Bug #484 CVE-2018-17582 Check for corrupt PCAP files

docs/CHANGELOG, src/common/utils.c, src/tcpedit/plugins/dlt_en10mb/en10mb.c
Also added check for packet size > cap len, although this may
be never be hit since #484
=> Bug #486 CVE-2018-17974 realloc memory if packet size increases

docs/CHANGELOG
Getting the following error message when attempting to reproduce bug:
tcpreplay -i ens33 --unique-ip -t --loop 4 fast_edit_package_02
safe_pcap_next ERROR: Invalid packet length in send_packets.c:get_next_packet() line 1054: packet length 28 is less than capture length 60
=> Bug #485 Heap overflow fixed in #484

configure.ac
This setting was being skipped when --with-testnic=xxx was specified to ./configure.
Also enables osx_frameworks var when the option is specified when building for OS X.  This should make the option have only the intended effect of setting test test nic values on the build.
There may be some other issues with the current structure.  E.g. lines such as AC_DEFINE([HAVE_LINUX], [1], [Building Linux]) are never reached with testnic defined.
=> Bug #474 enable pcap_findalldevs when --with-testnic is specified

src/common/netmap.h
As of netmap commit 7b16969f (version 10), should use nm_tx_pending()
to determine whether the TX buffers still contain data.
Fix is to use nm_tx_pending() rather than NETMAP_TX_RING_EMPTY,
unless using an older version of netmap.
=> Bug #424 Fix compatibility for netmap version 10 and higher

configure.ac, src/common/sendpacket.c, src/tcpreplay_opts.def
This fix will yield the CPU while netmap is waiting
for buffers.
On my test system, this improved performance by only
60Mbps, not the 4Gbps performance loss identified
by this bug. Therefore, this is not the final fix
for this bug.
=> Bug #528 Yield in netmap main loop

configure.ac, docs/CHANGELOG, src/common/utils.c
Add check for packets that report zero packet length. Example
of fix:
src/tcpprep --auto=bridge --pcap=poc16-get_l2len-heapoverflow --cachefile=/dev/null
Warning: poc16-get_l2len-heapoverflow was captured using a snaplen of 17 bytes.  This may mean you have truncated packets.
safe_pcap_next ERROR: Invalid packet length in tcpprep.c:process_raw_packets() line 334: packet length=0 capture length=0
=> Bug #520 Fix heap overflow on zero or 0xFFFF packet length

src/common/get.c
Hi,
Those are fix proposal for issues #536 and #537.
However, the #356 reproducer is in big endian for some reason, and when working on little endian, it fails to load because the read capture length is bigger than the maximum.
However both issues really look the same to me and the fixes are localized, so I'm confident about my proposal.
Please review.
Best regards
=> stability fixes

README.md, src/tcprewrite_opts.def
Update or remove references to Ethereal as appropriate. It was renamed
to Wireshark in 2006 and www.ethereal.com has been inaccessible for
several years.
Change a www.wireshark.org link to HTTPS.
=> Wireshark and Ethereal reference updates.

configure.ac, src/common/Makefile.am, src/tcpedit/plugins/dlt_jnpr_ether/Makefile.am, src/tcpedit/plugins/dlt_pppserial/Makefile.am
This removes files that were listed several times from the *_SOURCES
variables.
=> makefile: remove some duplicated SOURCES entries

libopts/boolean.c, libopts/configfile.c, src/common/flows.c, src/common/get.c, src/common/sendpacket.c, src/send_packets.c, src/sleep.h, src/tcpedit/tcpedit.c, src/tcpreplay_api.c, src/timestamp_trace.h
Hi,
In my setup, this leaves two warning:
A `cast-function-type` warnings caused by libpcap
In my opinion, the code calling libpcap is valid, and the warning can safely be ignored.
Another saying that the <sys/sysctl.h> header is deprecated and will be removed.
I'll just leave the warning for later.
Best regards,
=> gcc-10 warnings fixes

src/common/flows.c, src/common/get.c, src/send_packets.c, src/tcpedit/plugins/dlt_en10mb/en10mb.c
Fix for bug #583 
Several places where the calculation of the offset to the eth_hdr_t is actually jumping past the ethernet header (so that the VLAN tag is not correctly identified). It's the last one (src/tcpedit/plugins/dlt_en10mb/en10mb.c) that is the proximate cause of the issue with corrupting the IP flags field.
Be aware that there is some interaction with DLT_JUNIPER_ETHERNET in a couple of these spots that I'm unable to test.
=> Correct L2 header length calculations so that IP header offset is correct

src/tcpedit/fuzzing.c
Some fuzzer mutations do divide by zero when l4len equals to 1.
Note that the patch affects on fuzzer ability to fuzz packets where l4len equals to 1.
Tested on:
OS: Ubuntu 18.04 x64
```
./tcprewrite --version
tcprewrite version: 4.3.2 (build git:v4.3.2-5-g11507365)
Copyright 2013-2018 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.8.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: disabled
```
Minimized test case as an attachment. [FPE-6a2-06c-a94.zip](https://github.com/appneta/tcpreplay/files/3964782/FPE-6a2-06c-a94.zip)
To reproduce, …
=> Fix divide by zero in fuzzing

docs/CHANGELOG, src/send_packets.c
At very high iteration counts '--unique-ip' calculation
(which support floating point e.g. 0.75) has accuracy
issues. Corrected by converting to integer earlier,
and multiplying numerator/denominator by 1000.
=> Bug #566 Fix float to integer rounding issue

docs/CHANGELOG, src/fragroute/fragroute.c, src/fragroute/mod.c, src/fragroute/mod_ip_frag.c, src/fragroute/mod_tcp_seg.c, src/fragroute/pkt.h
Fragroute relies on down-level `lib/queue.h` which is
copied from older versions of FreeBSD. Depending on the
order of includes, some source files were using
it, and others were picking up `/usr/include/sys/queue.h`.
Fix is to ensure that there is a `lib/queue.h` include before
any `#include defines.h`
=> Bug #558 Restructure includes to pick up proper header

src/common/utils.c
If packet caplen > packet len, update caplen to equal len.
Although this appears to be impossible if trace was generated from
a reliable source (i.e. libpcap), there appears to be enough pressure
from the community to allow these invalid packets to be sent.
IMHO, I think that if a pcap is invalid, tcpreplay should fail. But it
appears that this is the behavior desired by users.
=> Bug #557 Attempt to correct corrupt packets

configure.ac, docs/CHANGELOG, src/common/sendpacket.c
Increase number of interfaces from 10 to 512. Now test
/dev/bpf0 to /dev/bpf511 to find and available BPF devices.
This fixes issues introduced in macOS Mojave (10.14).
=> Bug #550 Expand /dev/bpfX limit

docs/CHANGELOG, src/tree.c
Prevent heap buffer overflow by checking packet lengths
in packet2tree()
=> Bug #530 HBO in packet2tree()

src/defines.h.in
Depending on compilaiton flags, UNUSED() was declaring variables with
different names.
Meaning the following can be either expanded to:
`UNUSED(var)` -> `var`
`UNUSED(var)` -> `UNUSED_var __attribute__((unused))`
depending on the compilation flags.
The code using such a variable would need to also be conditional to the
same compilation flags ... and that's to heavy.
Let's declare variables by the name they are given instead.
`UNUSED(var)` -> `var` /* with/without the attribute, but always "var" */
Fixes #612
Signed-off-by: Gabriel Ganne <gabriel.ganne@gmail.com>
=> Fix UNUSED Macro declaration

docs/CHANGELOG, src/common/get.c
Also did some fixes to Juniper Ethernet protocols to fix some bugs
and support various types of Juniper Ethernet protocol types. Used
Wireshark sources to figure out all the different packet types that
Juniper uses.
Unable to test all types because of lack of JNPER DLT pcaps.
Also applied a fix for DLT_RAW to prevent similar issues.
=> Bug #616 Add checks for datalen for DLT_JUNIPER_ETHER

docs/CHANGELOG
=> Bug #617 CVE-2020-24266 fix tcpprep get_l2len()

docs/CHANGELOG, src/send_packets.c
Change calculation after high packet sent count. The updated
calculation will not work well for something like `--pps=0.1`
but that would take many years to overflow, even on 32-bit
machines.
=> Bug #629 Compensate for overflow on high pps tests

src/tcpedit/tcpedit.c
There is a small typo in src/tcpedit/tcpedit.c
`to short to contain` should read `too short to contain`
=> fixed simple typo, to short -> too short

libopts/autoopts/options.h, libopts/configfile.c, libopts/restore.c
There is a small typo in libopts/autoopts/options.h, libopts/configfile.c, libopts/restore.c.
Should read `hierarchically` rather than `hierarcicaly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, hierarcicaly -> hierarchically

src/tcpedit/tcpedit.c
Hi,
This is in response to #611
The ticket issue is caused by the packet being rewritten to be
unsupported (fragmented IPv6 packet). The issue would be the same
for malformed packets however.
The current behavior is to fail quite brutally by stopping all processing
right away. I propose to just skip those packets instead.
Best regards,
=> tcprewrite: handle malformed and unsupported packets as soft errors

src/common/utils.h, src/send_packets.c
Prior to this change, time between packets was calculated as deltas
and over time errors would quickly add up. The work here switches
to use the wall time since the first packet was sent as the reference
which is compared to the PCAP packet timestamp relative to the first
packet. In this way there are no errors and clock drift is avoided.
As a result tcpreplay can now be used to play back very time sensitive
captures such as video streams with PCR.
This is a suggested fix for https://github.com/appneta/tcpreplay/issues/630
=> send_packet: Avoid clock drift by using time since first packet

src/tcpreplay_api.c
```
cgs@idog-ubuntu:~/workspace/tcpreplay$ src/tcpreplay -i docker0 --pps abc --stats 1 tcp.pcap 
Warning: May need to run as root to get access to all network interfaces.
Fatal Error: Unable to parse args: invalid pps value 'abc'
```
=> Bug #632 fix pps invalid value protection

configure.ac
Allow the user to disable libdnet check through --without-libdnet.
This option is useful to cross-compile tcpreplay to avoid build failures
if libdnet is installed on host but not on target, see
https://bugs.buildroot.org/show_bug.cgi?id=12096
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix --without-libdnet

src/common/cidr.c, src/common/tcpdump.c, src/tcpprep.c
This #include and the #ifdef around it are both already inside the defines.h.in header
=> remove duplicate #include "lib/strlcpy.h"

lib/strlcat.c, lib/strlcpy.c
The other BSD functions in the /lib directory are outdated too but I'm not familiar with them and I haven't checked if there are any breaking changes to their interfaces.
Additionally, have you considered the [libbsd](https://libbsd.freedesktop.org/wiki/) library? It's a popular library so it's on pretty much every distro repo and it runs on Linux, Mac, and it doesn't run on Windows but there Cygwin provides BSD functions instead and Microsoft's WSL is just Ubuntu as far as we're concerned. 
The library provides all the BSD extensions in the /lib directory of tcpreplay's source tree and many more, it also has an "overlay" mode that introduces the functions in the same standard headers that the BSDs extend, and if the libc it was compiled for implements the functions it doesn't include …
=> Update strlcpy.c and strlcat.c

src/common/flows.c, src/common/get.c
=> Apply #616 fix to flows.c, fix #665

src/tcpreplay.c
Sometimes your pcaps are buried deep into some directories and sub-directories. Depending on how many you want to pass to tcpreplay and how long their name are, you may be limited by the shell command line length.
Of course you can do another directory with some symbolic links, but it can be more convenient that tcpreplay loads directly a directory or a list of directories.
=> Directories of pcaps as arguments

docs/CHANGELOG, src/common/utils.h, src/send_packets.c
This reverts commit ec50def8c84da9af2903ff878fd4d6d844f3efe0.
=> Bug #674 - Revert "send_packet: Avoid clock drift by using time since first packet"

docs/CHANGELOG, src/tcpreplay.c
Fixes regression due to feature #682 - Directories of pcaps as arguments
=> Bug #708 fix support for feeding PCAP files from STDIN

configure.ac
configure scripts are run with /bin/sh which is supposed
to be a POSIX-compliant shell, so if /bin/sh is provided
by e.g. dash (like on Debian) rather than bash, we hit
errors.
This has no effect on functionality for bash &
retains compatibility.
Signed-off-by: Sam James <sam@gentoo.org>
=> build: fix bashism in configure

docs/CHANGELOG, src/common/get.c, src/common/get.h, src/tcpedit/checksum.c, src/tcpedit/checksum.h, src/tcpedit/edit_packet.c, src/tcpedit/fuzzing.c, src/tcpedit/portmap.c, src/tcpedit/rewrite_sequence.c, src/tcpedit/tcpedit.c, src/tcpprep.c
Add end_ptr to key functions, which make it easier to implement
overflow protections.
=> Bug #718 improved heap-overflow protection

docs/CHANGELOG, src/tcpreplay.c, src/tcpreplay_api.c
Only for tcpreplay_edit. It is not well defined what should happen
when packets are both cached and edited. This forces packets to be
reloaded every loop iteration, resulting in edits on un-cached packets
every iteration.
=> Bug #729 tcpreplay_edit: disallow both -K and -l options

docs/CHANGELOG, src/send_packets.c
Sample output:
```
/Users/fklassen/git/tcpreplay/build/src/tcpreplay -i en0 -t pkt_too_long.pcap
Actual: 2 packets (196 bytes) sent in 0.000066 seconds
Rated: 2969696.9 Bps, 23.75 Mbps, 30303.03 pps
Flows: 2 flows, 30303.03 fps, 3 flow packets, 0 non-flow
Statistics for network device: en0
Successful packets:        2
Failed packets:            1
Truncated packets:         0
Retried packets (ENOBUFS): 0
Retried packets (EAGAIN):  0
Warning in /Users/fklassen/git/tcpreplay/src/send_packets.c:send_packets() line 489:
Unable to send packet: Error with bpf send() [2]: Input/output error (errno = 5)
Process finished with exit code 0
```
=> Bug #751 don't exit after send error

configure.ac
Do not call exit without declaring it.  Add #include <unistd.h> for fork.  Add missing int type to the definition of main.
Implicit ints and implicit function declarations were removed from C in 1999 and will not be supported by future compilers.
=> configure.ac: Avoid implicit int, implicit function declarations

.gitignore, docs/CHANGELOG, src/tcpreplay.c
Flow, fps, flow packet counts make sense for many combinations of packet modifiers and cache settings:
```
Actual: 16 packets (1568 bytes) sent in 0.012564 seconds
Rated: 124801.0 Bps, 0.998 Mbps, 1273.47 pps
Flows: 2 flows, 159.18 fps, 16 unique flow packets, 0 unique non-flow packets
Statistics for network device: enp0s5
Successful packets:        16
Failed packets:            0
Truncated packets:         0
Retried packets (ENOBUFS): 0
Retried packets (EAGAIN):  0
File Cache is enabled
Actual: 16 packets (1568 bytes) sent in 0.012561 seconds
Rated: 124830.8 Bps, 0.998 Mbps, 1273.78 pps
Flows: 2 flows, 159.22 fps, 16 unique flow packets, 0 unique non-flow packets
Statistics for network device: enp0s5
Successful packets:        16
Failed packets:            0
Truncated packets:         0 …
```
=> Bug #749 flow stats: avoid overstating flow packet count

docs/CHANGELOG, test/Makefile.am, test/config.in
e.g.
```
mkdir build
cd build
autoreconf --install --force --verbose ..; ../configure --disable-local-libopts --with-testnic=enp0s5
make
sudo make test
```
=> Bug #767 tests: support for out-of-tree tests

src/tcpedit/plugins/dlt_jnpr_ether/jnpr_ether.c
=> dlt_jnpr_ether_cleanup: check subctx before cleanup

src/tcpedit/plugins/Makefile.am, src/tcpedit/plugins/dlt_linuxsll2/Makefile.am, src/tcpedit/plugins/dlt_linuxsll2/linuxsll2.c, src/tcpedit/plugins/dlt_linuxsll2/linuxsll2.h, src/tcpedit/plugins/dlt_linuxsll2/linuxsll2_opts.def, src/tcpedit/plugins/dlt_linuxsll2/linuxsll2_types.h, src/tcpedit/plugins/dlt_plugins.c, src/tcpedit/plugins/dlt_stub.def
=> Add support for LINUX_SLL2

docs/CHANGELOG, src/common/sendpacket.c, src/send_packets.c
I'm not sure why PPS overflow protection was not implemented for lower rates. This fix makes the overflow protection always available.
Also fix a compile warning.
=> Bug #779 - honour overflow for all PPS values

configure.ac, src/common/sendpacket.c, src/common/sendpacket.h, src/defines.h.in, src/send_packets.c, src/send_packets.h, src/tcpreplay_api.c, src/tcpreplay_api.h, src/tcpreplay_opts.def
The aim of this change is to extend existing packet sending methods with AF_XDP socket using libxdp api.
By using AF_XDP socket, the time needed for packet sending can be decreased substantially.
- all the relevant changes are inside a #ifdef HAVE_LIBXDP guard 
- --batch-size flag is introduced to tcpreplay interface. AF_XDP socket is used typically with batch of packets, the default value is 25 however the user can set it using --batch-size flag, the maximum value is set to 4096 now (see my reasoning at the very end of this comment). 
- Due to batch processing feature tcpr_sleep will be called only in case --batch-size=1, since it doesn't make sense to sleep the relative time between two packets when batch-size is higher than 1. 
- Due to batch processing feature statistics calculated …
=> AF_XDP socket extension using libxdp api

src/common/get.c
**Description:**
Handle IPv6 fragment extension header
only return NULL when reached end of packet (no data)
**Explanation:**
When issue #488 was fixed (pr #496) (version=4.3.0, and carried forward to version=4.4.0), the fix prevented IPv6
fragment extension header handling. The need was to prevent addressing headers beyond packet length (to avoid
heap corruption). However, the fix prevents any further processing of the packet after fragment extension header found.
When the extension header `proto=TCPR_IPV6_NH_FRAGMENT`, we can skip that header (fixed length=32 bits),
process any further extension headers, and return a pointer to packet data.
When issue #611 was fixed (pr #613), the solution was to leave any IPv6 packets with fragment extension header
untouched (and generate …
=> Handle IPv6 fragment extension header

configure.ac
* add lib32 because when building lib32-tcpreplay it's impossible to set --with-libpcap so that it would find both include files as well as the library in lib32 directory
* maybe it would be beneficial to split --with-libpcap into --with-libpcap-includedir --with-libpcap-libdir as this already searches in the --with-libpcap value with and without any "lib" prefix, but include files always expect "include" dir there
* most of this code was added in: https://github.com/appneta/tcpreplay/commit/202b8e82f9fd3c84ce5804577caeb36a33baabe7#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R570
* then search for ${host_cpu} lib/${host_cpu} (without -${host_os} suffix) and ${build_arch}-${host_os} lib/${build_arch}-${host_os} was added, but only for search of dynamic library in: …
=> configure.ac: unify search dirs for pcap and add lib32

src/send_packets.c, src/tcpreplay_api.c, src/tcpreplay_api.h, src/tcpreplay_opts.def
- Add `--skip-pkts x` as parameter to `tcpreplay`. It adds support for skipping the first X packets in a pcap file
- Add `--skip-to-secs Y` as parameter to `tcpreplay`. It adds support for skipping until Y seconds into the pcap file. The seconds is absolute since since the unix epoch
We needed this in a project where we used a series of pcap files for storing sound and video recordings. If a user wanted to start a replay from a certain date and time we would know which pcap file to replay (based on the filename of the pcap file) and by using `--skip-to-seconds` we could jump to the date and time in the pcap file.
=> Add --skip-pkts and --skip-to-secs to allow skipping packets when replaying

src/common/cidr.c
This causes tcprewrite to exit with an error instead of crashing.
Fixes: #824
=> add check for empty cidr

libopts/m4/libopts.m4
Autoconf flagged AC_HELP_STRING as obsolete [1]
Replace with AS_HELP_STRING [2] which was introduced in 2.69 which is the current PREREQ.
[1] https://www.gnu.org/software/autoconf//manual/autoconf-2.69/html_node/Obsolete-Macros.html#Obsolete-Macros
[2] https://www.gnu.org/software/autoconf//manual/autoconf-2.69/html_node/Pretty-Help-Strings.html#AS%5fHELP%5fSTRING
=> autotools - AC_HELP_STRING is obsolete in 2.70

configure.ac
It'll give us nothing but error like below:
./conftest: cannot execute binary file: Exec format error
...
./configure: line 23950: test: -eq: unary operator expected
The version check only has effect on Apple systems. We'd better avoid error like above when cross compilation.
Also, in case of cross compilation, instead of having the above Exec format error and resulting in unaligned_cv_fail to yes, set it directly to yes.
=> configure.ac: do not run conftest in case of cross compilation

src/tcpedit/plugins/dlt_jnpr_ether/jnpr_ether.c
Fix #812 
The `ctx->encoder->config` is somehow already cleaned up in `dlt_en10mb_cleanup()` and set as `NULL`, so I add a check in `dlt_jnpr_ether_cleanup()`.
```
(gdb) p & ctx->encoder->config
$1 = (void **) 0x55555559f140
(gdb) watch *0x55555559f140
Hardware watchpoint 2: *0x55555559f140
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/ubuntu178/afgen/tcpreplay/4.4.4/bin_normal/bin/tcprewrite -o /dev/null --dlt=enet --enet-dmac=00:12:13:14:15:16,00:22:33:44:55:66 --enet-smac=00:12:13:14:15:16,00:22:33:44:55:66 -i issue-812
Warning: issue-812 was captured using a snaplen of 50 bytes.  This may mean you have truncated packets.
Hardware watchpoint 2: *0x55555559f140
Old value = <unreadable>
New value = 0 …
```
=> dlt_jnpr_ether_cleanup: check config before cleanup

src/tcpedit/plugins/dlt_plugins.c
Assume a single tcpedit struct and return the previously allocated context if called twice.
This fixes an issue with the Juniper Encapsulated Ethernet DLT plugin which has an exception in the way the plugins works with regard to the extra buffer in question: tcpreplay works with the assumption that there only ever is a single link layer plugin which is mostly true except here: Juniper has a special call to tcpedit_dlt_copy_decoder_state() which causes the ctx and subctx to share a reference to the decoded_extra buffer, and a double free.
Fixes: #813 #850
=> Fix recursive tcpedit cleanup

docs/CHANGELOG, src/tcpedit/plugins/dlt_en10mb/en10mb.c
SLL (Linux cooked packets v1) caused a crash due to an overly aggressive assert.
While here, fixed an issue where resultant packets were corrupt (wrong size, incorrect protocol)
=> Bug #792 avoid assertion and other fixes

docs/CHANGELOG, src/common/sendpacket.c
This ioctl error suggests that the tap interface has already been set.
Backed out #411 and #651 as they only partially address the issue and introduced new bugs.
=> Bug #844 tap: ignore TUNSETIFF EBUSY errors

docs/CHANGELOG, docs/INSTALL, src/tcpedit/tcpedit.c, src/tcpreplay_api.c
=> Bug #876 - add missing free_umem_and_xsk function

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/github-actions-ci.yml, configure.ac, docs/CHANGELOG, src/tcpedit/portmap.c, src/tcpreplay_opts.def, test/Makefile.am
Required to analyse rewrite issues in CI that are not otherwise reproducible.
Format is as per suggestion for Wireshark hex input, but I find it easier to convert to binary, e.g.
```
xxd -r failed_text.hex > failed.pcap
```
- [...]
...
=> Bug #933 ci: hexdump failing pcap on test failure

docs/CHANGELOG, src/tcpreplay_opts.def
If you use --xdp-batch-size other than 1, cannot control speed. Change default from 25 to 1.
Also require --topspeed if --xdp-batch-size is specified.
=> Bug #896 AF_XDP: default --xdp-batch-size=1

docs/CHANGELOG, src/common/txring.c, src/common/txring.h
similar issue in gcc 15 build environment.
- See more details at: http://errors.yoctoproject.org/Errors/Details/851800/
```
TOPDIR/tmp/work/core2-64-oe-linux/tcpreplay/4.5.1/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/15.0.1/ld: ./common/libcommon.a(sendpacket.o): in function `sendpacket':
/usr/src/debug/tcpreplay/4.5.1/src/common/sendpacket.c:328:(.text+0x1be): undefined reference to `txring_put'
TOPDIR/tmp/work/core2-64-oe-linux/tcpreplay/4.5.1/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/15.0.1/ld: ./common/libcommon.a(sendpacket.o): in function `sendpacket_open_pf':
/usr/src/debug/tcpreplay/4.5.1/src/common/sendpacket.c:1088:(.text+0x7ea): undefined reference to `txring_init' …
```
=> Bug #731 #904 various TX_RING link errors

configure.ac
=> configure.ac: Fixup the libpcap search loops.

configure.ac, docs/CHANGELOG, docs/CREDIT
=> Bug #905 configure libpcap search fix

src/common/sendpacket.h
```
In file included from ../../src/common/sendpacket.h:30: 
/usr/include/netinet/if_ether.h:154:17: fatal error: field has incomplete type 'struct arphdr'
struct   arphdr ea_hdr;                 /* fixed-size header */
^
/usr/include/netinet/if_ether.h:154:10: note: forward declaration of 'struct arphdr'
struct   arphdr ea_hdr;                 /* fixed-size header */
^
1 error generated.
```
=> Fix building on OpenBSD

docs/CHANGELOG, src/common/get.c
- do not fail on l2len == 0
...
=> Bug #911 continue on get l2len protcol is zero

src/common/txring.c, src/common/txring.h
- Change `txring.c`, `txring.h`
- Ensure txring compiles correctly to avoid linker errors.
- The result of "nm -u txring.o" shows no symbols exist.
- The config.h has HAVE_TX_RING defined but txring.c is not aware of it.
txring.c and txring.h include config.h at the beginning.
- Modify the assignment target for the `safe_malloc` return value from `*txp` to `txp`.
- This resulted in a successful build in my build environment.
=> fix compile, linker error for txring

docs/CHANGELOG, docs/CREDIT
- Change `txring.c`, `txring.h`
- Ensure txring compiles correctly to avoid linker errors.
- The result of "nm -u txring.o" shows no symbols exist.
- The config.h has HAVE_TX_RING defined but txring.c is not aware of it.
txring.c and txring.h include config.h at the beginning.
- Modify the assignment target for the `safe_malloc` return value from `*txp` to `txp`.
- This resulted in a successful build in my build environment.
=> Bug #924 TX_RING: Compile issue

docs/CHANGELOG, src/common/flows.c
- check IPv6 flow version header with proper offset
=> Bug #899 flows: correct IPv6 header version check

docs/CHANGELOG, lib/queue.h, src/fragroute/mod.c, src/fragroute/pkt.h
GCC 4.4.4 requires headers in a specific order to achieve compile on FreeBSD.
Move to `#pragma once` fixes, but also reorder headers as described by others.
- switch queue.h to `#pragma once`
- reorder some include headers
=> Bug #809 workaround for gcc 4.4.4 failure on FreeBSD

src/Makefile.am
It appears that some versions of automake will not regenerate defines.h unless BUILD_SOURCES is properly set.
Tested on Linux Rhino 2025.3
=> Bug #947 - ensure defines.h is always regenerated

docs/CHANGELOG, src/common/sendpacket.h
In virtio-net it appear to have faulty XDP support, in which case we get EINVAL.
Note that this may have been fixed in July 2025 with this commit. It touches some XDP code.
```
Mon Jul 7 04:14:54 2025 -0400 6aca3dad2145 virtio-net: ensure the received length does not exceed allocated size  [Bui Quang Minh]
``
=> Bug #956 XDP - fail with a more informative error message

configure.ac, docs/CHANGELOG, src/common/sendpacket.h, src/tcpedit/edit_packet.c, src/tcprewrite.c
No need to realloc if buffer is already proven to be big enough.
=> Bug #970 tcprewrite: --fixlen: do not use realloc
