src/common/utils.c

It looks like the code for outputting the stats could stand to
be refactored a bit, but this fix kicks the can down the road
a little futher.

Fixes an issue with Rated pkt stats overflowing.

---

docs/CHANGELOG
src/common/cache.c
src/tcpprep.c

restoring functionality lost in 4.1.1.beta2

#167 restore deleted code, test against v3.4.4

---

src/common/fakepoll.h
src/common/sendpacket.c

Fix compilation with musl c library

---

README.md
docs/CHANGELOG
src/common/cache.c
src/common/cidr.c
src/common/get.c
src/common/interface.c
src/common/mac.c
src/common/sendpacket.c
src/common/services.c
src/common/tcpdump.c
src/common/utils.c
src/replay.c
src/send_packets.c
src/tcpbridge.c
src/tcpedit/edit_packet.c
src/tcpedit/portmap.c
src/tcpliveplay.c
src/tcpprep_api.c
src/tree.c

Enhancement 305 coverity fixes

---

README.md
src/common/cache.c
src/common/cidr.c
src/common/interface.c
src/common/sendpacket.c
src/common/sendpacket.h
src/send_packets.c
src/tcpedit/checksum.c
src/tcpedit/edit_packet.c
src/tcpedit/plugins/dlt_jnpr_ether/jnpr_ether.c
src/tcpedit/plugins/dlt_jnpr_ether/jnpr_ether_types.h
src/tcpedit/plugins/dlt_pppserial/pppserial.c
src/tcpedit/plugins/dlt_pppserial/pppserial_types.h
src/tcpedit/portmap.c
src/tcpliveplay.c
src/tcpprep.c

Kick off another Coverity build

305 fix additional coverity bugs

---

src/common/cidr.c
src/common/interface.c

305 fix tests

---

src/common/utils.c
src/common/utils.h
src/config.h.in
src/tcpedit/plugins/dlt_en10mb/en10mb.c
src/tcpedit/plugins/dlt_en10mb/en10mb.h
src/tcpedit/plugins/dlt_en10mb/en10mb_opts.def
src/tcpedit/plugins/dlt_en10mb/en10mb_types.h

Add some options to rewrite MAC addresses.

MAC rewriting capabilities

---

src/tcpedit/tcpedit_opts.def

Improve fuzzing documentation for #320

improve fuzzing documentation

---

docs/CHANGELOG

Release 4.2.0beta2

---

src/common/flows.c

for all datalinks, check whether caplen > l2 header len
this should fix issues #407 #408 #409 #410

fix heap-buffer-overflow in flow_decode()

---

src/common/cache.c

Fix tcpprep failure for pcap with 1020+ pakcets

---

src/common/sendpacket.c
src/common/services.c
src/tcpliveplay.c

Fixed: #480
Signed-off-by: GwanYeong Kim <gy741.kim@gmail.com>

Remove dead code

---

src/send_packets.c

Add safety and failure reporting for packet captures with
caplen too small.

Bug #620 apply get.c functions fixed in #617

---

src/tree.c

This bit of code was screaming for a strlcpy.

replace memset followed by strncpy with strlcpy

---

docs/CREDIT

As talked about in #648 
I assume you fill in the details? I'm not sure how this was supposed to be done exactly.

add myself to CREDIT

---

configure.ac

* rename --macosx-sdk to --macos-sdk
* fix --macos-sdk
* if not specified, select latest SDK

Bug #668 Improve SDK selection

---

Makefile.am
configure.ac
docs/CHANGELOG

Bug #745 remove autogen.sh from distribution tarballs

---

src/common/cidr.c
src/common/list.c
src/common/mac.c
src/common/utils.c
src/tcpedit/portmap.c

Fix #782 #784 #785 #786 #787 #788

Fix bugs caused by strtok_r

---

src/common/get.c

ipv6 - add check for extension header length

---

docs/CHANGELOG
src/common/err.c
src/common/err.h
src/tcpbridge.c
src/tcpbridge_opts.def
src/tcpprep.c
src/tcpprep_api.c
src/tcpprep_opts.def
src/tcpreplay_api.c
src/tcpreplay_opts.def
src/tcprewrite.c
src/tcprewrite_opts.def

Feature #878 - add -w / --suppress-warning option
